models/User.php
<?php

namespace app\models;

class User extends \yii\base\BaseObject implements \yii\web\IdentityInterface
{
    public $id;
    public $username;
    public $password;
    public $authKey;
    public $accessToken;

    private static $users = [
        '100' => [
            'id' => '100',
            'username' => 'admin',
            'password' => '0912',
            'authKey' => 'test100key',
            'accessToken' => '100-token',
        ],
    ];


    /**
     * {@inheritdoc}
     */
    public static function findIdentity($id)
    {
        return isset(self::$users[$id]) ? new static(self::$users[$id]) : null;
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        foreach (self::$users as $user) {
            if ($user['accessToken'] === $token) {
                return new static($user);
            }
        }

        return null;
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        foreach (self::$users as $user) {
            if (strcasecmp($user['username'], $username) === 0) {
                return new static($user);
            }
        }

        return null;
    }

    /**
     * {@inheritdoc}
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * {@inheritdoc}
     */
    public function getAuthKey()
    {
        return $this->authKey;
    }

    /**
     * {@inheritdoc}
     */
    public function validateAuthKey($authKey)
    {
        return $this->authKey === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return $this->password === $password;
    }
}

controllers/AdminController.php
<?php
/**
 * Created: 15.04.18
 */

namespace app\controllers;

use app\models\db\UserRequest;
use app\models\form\LoginForm;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;

class AdminController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['logout', 'user-request'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['user-request'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionUserRequest()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => UserRequest::find()->orderBy(['id' => SORT_DESC]),
        ]);

        return $this->render('user_request', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionUserRequestProcess($id)
    {
        $user_request = UserRequest::findOne(['id' => $id]);
        if ($user_request !== null) {
            $user_request->is_new = 0;
            $user_request->save();
        }

        return $this->redirect(Yii::$app->request->referrer ?: ['/admin/request']);
    }
}

controllers/FormController.php
<?php
/**
 * Created: 03.06.18
 */

namespace app\controllers;


use app\models\form\UserRequestForm;
use Yii;
use yii\filters\ContentNegotiator;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\Response;

class FormController extends Controller
{
    public function behaviors()
    {
        return [
            'bootstrap' => [
                'class' => ContentNegotiator::class,
                'formats' => [
                    'application/json' => Response::FORMAT_JSON,
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'user-request'  => ['post'],
                ],
            ],
        ];
    }

    public function actionUserRequest()
    {
        $user_request = new UserRequestForm();
        if ($user_request->load(Yii::$app->request->post()) && $user_request->save()) {
            return ['success' => true, 'message' => 'Заявка успешна отправлена!'];
        }

        return ['success' => false, 'message' => $user_request->getError()];
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\behaviors\UserTrackerBehavior;
use app\models\db\UserRequest;
use app\models\db\UserTracker;
use app\models\form\UserRequestForm;
use Yii;
use yii\web\Controller;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            [
                'class' => UserTrackerBehavior::class,
                'model_class' => \app\models\db\UserTracker::class,
            ]
        ];

    }


    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $user_request = new UserRequestForm();

        if (!Yii::$app->user->isGuest) {
            $number_new_requests = UserRequest::getNumberNewRequests();
            $number_visitors_per_day = UserTracker::getNumberVisitorsPerDay();
        }

        $number_new_requests = $number_new_requests ?? false;
        $number_visitors_per_day = $number_visitors_per_day ?? false;

        return $this->render('index', [
            'user_request' => $user_request,
            'number_new_requests' => $number_new_requests,
            'number_visitors_per_day' => $number_visitors_per_day,
        ]);
    }
}

controllers/TelegramController.php
<?php
/**
 * Created: 10.10.2020
 */

namespace app\controllers;


use app\models\db\TelegramBot;
use DateTime;
use DateTimeZone;
use Yii;
use yii\helpers\Json;
use yii\helpers\Url;
use yii\web\Controller;

class TelegramController extends Controller
{
    public $enableCsrfValidation = false;

    /**
     *  Экшен устанавливает урл для вебхук
     */
    public function actionSetWebhook()
    {
        $url = "https://jaluzi-barnaul.ru" . Url::to(['telegram/webhook']);

        echo "<pre>";
        print_r(array_merge((array) Yii::$app->telegram->setWebhook(['url' => $url]), [
            'url' => $url,
        ]));
        echo "</pre>";
    }

    public function actionWebhook()
    {
        $body = Yii::$app->request->getRawBody();
        $data = Json::decode($body);
        $this->logToFile("\n\nIncome: \n" . print_r($data, 1), 'webhook');

        TelegramBot::reply($data);
    }

    protected function logToFile($message, $prefix)
    {
        $log_dir = Yii::getAlias('@runtime') . '/logs/telegram';

        if (!is_dir($log_dir)) {
            mkdir($log_dir);
        }

        $date = new DateTime('now', new DateTimeZone('Asia/Novosibirsk'));
        $log = $log_dir . '/' . $prefix . '_' . $date->format('m-Y') . '.log';
        $message = "\n\n" . "[" . $date->format('Y-m-d H:i:s') . "]" . "\n" . $message;
        $result = $fp = fopen($log, 'a');

        if ($fp) {
            $result = fwrite($fp, $message);
            fclose($fp);
        }

        return (boolean) $result;
    }
}

views/admin/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">
    <div class="row">
        <h1><?= Html::encode($this->title) ?></h1>

        <p>Please fill out the following fields to login:</p>

        <?php $form = ActiveForm::begin([
            'id' => 'login-form',
            'layout' => 'horizontal',
            'fieldConfig' => [
                'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
                'labelOptions' => ['class' => 'col-lg-1 control-label'],
            ],
        ]); ?>

            <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

            <?= $form->field($model, 'password')->textInput() ?>

            <?= $form->field($model, 'rememberMe')->checkbox([
                'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
            ]) ?>

            <div class="form-group">
                <div class="col-lg-offset-1 col-lg-11">
                    <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>
            </div>

        <?php ActiveForm::end(); ?>
    </div>
</div>

views/admin/user_request.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use \yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

?>
<div class="group-promo-code-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="container">
        <div class="row">
            <div class="col-sm-2"><a href="/" class="btn btn-info">Назад</a></div>
        </div>

        <div class="row">
            <div class="col-sm-12">
                <?= GridView::widget([
                    'dataProvider' => $dataProvider,
                    'rowOptions' => function (\app\models\db\UserRequest $model, $key, $index, $grid) {
                        if ($model->is_new) {
                            return ['style' => 'background-color: #A0D6B4;'];
                        }
                        return [];
                    },
                    'columns' => [
                        'name',
                        'phone',
                        'email',
                        'created_at',
                        [
                            'label' => 'Новая',
                            'value' => function($model) {
                                $result = 'Да';
                                if ($model->is_new == 0) {
                                    $result = 'Нет';
                                }
                                return $result;
                            },
                        ],

                        [
                            'class' => 'yii\grid\ActionColumn',
                            'header' => 'Действия',
                            'headerOptions' => ['style' => 'color:#337ab7'],
                            'template' => '{processed}',
                            'buttons' => [
                                'processed' => function ($url, $model) {
                                    return Html::a('Обработана', $url);
                                },

                            ],
                            'urlCreator' => function ($action, $model, $key, $index) {
                                if ($action === 'processed') {
                                    return Url::to(['/admin/user-request-process', 'id' => $model->id]);
                                }
                            }
                        ],
                    ],
                ]); ?>
            </div>
        </div>
    </div>
</div>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

    <?= $content ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/** @var $this \yii\web\View*/
/** @var $user_request \app\models\form\UserRequestForm*/
/** @var $number_new_requests integer*/
/** @var $number_visitors_per_day integer*/


use \yii\helpers\Html;

$this->title = '"OOO" Дом-Сервис';

\Yii::$app->view->registerMetaTag([
    'name' => 'description',
    'content' => '"ООО" Дом-Сервис - ',
]);

\Yii::$app->view->registerMetaTag([
    'name' => 'keywords',
    'content' => 'Жалюзи Барнаул, жалюзи барнаул, жалюзи барнаул цена, лучшие жалюзи барнаул, дешевые жалюзи Барнаул, горизонтальные жалюзи барнаул, Москитные сетки Барнаул, москитные сетки барнаул, москитные сетки барнаул цена',
]);

?>

<!-- for gluing together -->
<section id="home"></section>
<div class="wrapper">
    <?= $this->render('sections/navigation', ['number_new_requests' => $number_new_requests, 'number_visitors_per_day' => $number_visitors_per_day]) ?>
    <?= $this->render('sections/main', ['user_request' => $user_request]) ?>
    <?= $this->render('sections/sale') ?>
    <?= $this->render('sections/production') ?>
    <hr>
    <?= $this->render('sections/why_we') ?>
    <?= $this->render('sections/contact') ?>
    <footer id="footer">
        <div class="container">
            <figure>(C) "ООО" ДОМ-СЕРВИС 2006-<?= date('Y') ?></figure>
        </div>
    </footer>
</div>

views/site/sections/contact.php
<?php
/**
 * Created: 28.05.18
 */

use yii\helpers\Html;

?>
<section id="contact" class="block background-color-grey-dark has-dark-background">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-4">
                <header><h3>Контакты</h3></header>
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-6">
                        <address>
                            <strong>График работы:</strong><br>
                            Пн: 09:00 - 18.00 <br>
                            Вт: 09:00 - 18.00 <br>
                            Ср: 09:00 - 18.00 <br>
                            Чт: 09:00 - 18.00 <br>
                            Пт: 09:00 - 18.00 <br>
                            Сб: выходной <br>
                            Вс: выходной <br>
                        </address>
                    </div>
                    <div class="col-md-12 col-sm-12 col-xs-6">
                        <address>
                            <strong>"ООО" Дом-Сервис</strong><br>
                            Северо-Западная, 39 <br>
                            Барнаул<br>
                            <abbr title="Телефон">Т:</abbr> +7 (3852) 362‒313 <br>
                            <abbr title="Телефон">Т:</abbr> +7 983 608-90-83 <br>
                            <abbr title="Email">E:</abbr> <a href="mailto:triotaln@mail.ru">triotalan@mail.ru</a>
                        </address>
                    </div>
                </div>
            </div>
            <div class="col-md-8 col-sm-8">
                <?= Html::img(Yii::getAlias('@web') .'/img/location.png', ['class' => 'img-fluid img-responsive']) ?>
            </div>
        </div>
    </div>
</section>

views/site/sections/main.php
<?php
/** @var $this \yii\web\View*/
/** @var $user_request \app\models\form\UserRequestForm*/

use yii\helpers\Html;

?>
<section id="slider">
    <div class="flexslider">
        <ul class="slides">
            <li class="slide"><?= Html::img(Yii::getAlias('@web') .'/img/jaluzi.jpg') ?></li>
        </ul><!-- /.slides -->
    </div><!-- /.flexslider -->
    <div class="slider-banner">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-sm-8">
                    <div class="title">
                        <h2>Лучшие жалюзи в Барнауле!</h2>
                        <figure class="subtitle">Заполните форму и в течение 5 минут наш менеджер свяжется с Вами!</figure>
                    </div><!-- for gluing together -->
                </div><!-- for gluing together -->
                <div class="col-md-4 col-sm-4">
                    <div class="form-slider-wrapper">
                        <?= $this->render('main/_user_request_form', [
                                'user_request' => $user_request,
                            ]) ?>
                    </div><!-- for gluing together -->
                </div><!-- for gluing together -->
            </div><!-- for gluing together -->
        </div><!-- for gluing together -->
    </div><!-- for gluing together -->
</section><!-- for gluing together -->

views/site/sections/main/_user_request_form.php
<?php

/** @var $user_request \app\models\form\UserRequestForm*/

use \yii\helpers\Html;
?>

<?= Html::beginForm(
        ['form/user-request'],
        'post',
        ['id' => 'form-slider', 'data-sform' => 1, 'data-submit-btn' => '#form-slider-submit']
); ?>
    <header>
        <h3>Обратный звонок</h3>
        <span class="success-form"></span>
        <span class="error-form"></span>
    </header>
    <hr>
    <div class="form-group">
        <label for="name"><?= $user_request->getAttributeLabel('name') ?><em>*</em></label>
        <?= Html::activeInput(
            'text',
            $user_request,
            'name',
            ['id' => 'name', 'class' => 'form-control']
        )?>
    </div><!-- for gluing together -->
    <div class="form-group">
        <label for="email"><?= $user_request->getAttributeLabel('phone') ?><em>*</em></label>
        <?= Html::activeInput(
            'text',
            $user_request,
            'phone',
            ['id' => 'phone', 'class' => 'form-control']
        ) ?>
    </div><!-- for gluing together -->
    <div class="form-group">
        <label for="phone"><?= $user_request->getAttributeLabel('email') ?></label>
        <?= Html::activeInput(
            'text',
            $user_request,
            'email',
            ['id' => 'email', 'class' => 'form-control']
        ) ?>
    </div><!-- for gluing together -->
    <div class="form-group">
        <div id="form-slider-status"></div>
        <?= Html::submitButton(
            $user_request->getAttributeLabel('submit'),
            ['id' => 'form-slider-submit', 'class' => 'btn btn-default']
        ) ?>
    </div><!-- for gluing together -->
    <figure>*Обязательные поля</figure>
<?= Html::endForm() ?>

views/site/sections/navigation.php
<?php

/** @var $number_new_requests integer*/
/** @var $number_visitors_per_day integer*/

use yii\helpers\Html;

?>

<div class="navigation fixed" style="position: fixed !important;">
    <div class="container">
        <header class="navbar" id="top" role="banner">
            <div class="navbar-header">
                <button id="js-mobile-menu" class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
                    <span class="sr-only">Показать меню</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="navbar-brand nav" id="brand">
                    "ООО" Дом-сервис
                    <?php if ($number_visitors_per_day !== false): ?>
                        <span class="label label-default"><?= $number_visitors_per_day ?></span>
                        <span class="label label-warning"><?= $number_new_requests ?></span>
                    <?php endif; ?>
                </div>
            </div>
            <nav class="collapse navbar-collapse bs-navbar-collapse navbar-right" role="navigation">
                <ul id="js-nav" class="nav navbar-nav">
                    <li class="active"><a href="#home">Главная</a></li>
                    <li><a href="#sale">Акция</a></li>
                    <li><a href="#properties">Продукция</a></li>
                    <li><a href="#features">Почему мы</a></li>
                    <li><a href="#contact">Контакты</a></li>
                    <?php if (!Yii::$app->user->isGuest): ?>
                        <li><?= Html::a('Запросы', ['/admin/user-request']) ?></li>
                        <li><?= Html::a('Выйти', ['/admin/logout'], ['data' => ['method' => 'post']]) ?></li>
                    <?php endif; ?>
                </ul>
            </nav><!-- for gluing together -->
        </header><!-- for gluing together -->
    </div><!-- for gluing together -->
</div><!-- for gluing together -->

views/site/sections/production.php
<?php
/**
 * Created: 28.05.18
 */
?>

<section id="properties" class="block">
    <div class="container">
        <header><h3>Продукция</h3></header>
        <?= $this->render('production/items') ?>
    </div><!-- for gluing together -->
</section><!-- for gluing together -->

views/site/sections/production/items.php
<?php
/**
 * Created: 20.05.18
 */

use yii\helpers\Html;

$production = [
    [
        'img' => 'gorizontal.jpg',
        'title' => 'Горизонтальные',
        'description' => '<dl>
                            <dt>Белые</dt>
                            <dd>от 1750 руб / м<sup>2</sup></dd>
                            <dt>Цветные</dt>
                            <dd>от 2700 руб / м<sup>2</sup></dd>
                        </dl>',
    ],
    [
        'img' => 'vertical.jpg',
        'title' => 'Вертикальные',
        'description' => '<dl>
                            <dt>Эконом</dt>
                            <dd>от 1400 руб / м<sup>2</sup></dd>
                            <dt>Элит</dt>
                            <dd>от 1700 руб / м<sup>2</sup></dd>
                        </dl>',
    ],
    [
        'img' => 'rulon-shtora.jpg',
        'title' => 'Рулонная штора',
        'description' => '<dl>
                            <dt>Blackout</dt>
                            <dd>от 1500 руб за створку</dd>
                            <dt>Затеняющие</dt>
                            <dd>от 1300 руб</dd>
                        </dl>',
    ],
    [
        'img' => 'rol_stavni.jpg',
        'title' => 'Рольставни',
        'description' => '<dl>
                            <dt>Белые</dt>
                            <dd><i>цена договорная</i></dd>
                            <dt>Цветные</dt>
                            <dd><i>цена договорная</i></dd>
                        </dl>',
    ],
    [
        'img' => 'garagnie_vorota.jpg',
        'title' => 'Гаражные ворота',
        'description' => '<dl>
                            <dt>Aлютех</dt>
                            <dd><i>цена договорная</i></dd>
                            <dt>Damast</dt>
                            <dd><i>цена договорная</i></dd>
                        </dl>',
    ],
    [
        'img' => 'setka.jpg',
        'title' => 'Москитные сетки',
        'description' => '<dl>
                            <dt>Ремонт</dt>
                            <dd>450 руб</dd>
                            <dt>Изготовление</dt>
                            <dd>от 1000 руб</dd>
                        </dl>',
    ],
    [
        'img' => 'balcon.jpeg',
        'title' => 'Остекление балконов и лоджий',
        'description' => '<dl>
                            <dt>Из ПВХ или Алюминия</dt>
                            <dd style="visibility: hidden"> - </dd>
                        </dl>',
    ],
    [
        'img' => 'bambuk.jpg',
        'title' => 'Бамбуковые',
        'description' => '<dl>
                            <dt>Изготовление</dt>
                            <dd>от 2850 руб/ м<sup>2</sup></dd>
                        </dl>',
    ],
    [
        'img' => 'minikaseta.jpg',
        'title' => 'Миникасеты',
        'description' => '<dl>
                            <dt>Изготовление</dt>
                            <dd>от 1850 руб</dd>
                        </dl>'
    ]
];

?>

<div class="row">
<?php foreach ($production as $item): ?>
    <div class="col-md-4 col-sm-4">
        <div class="property-wrapper">
            <div class="property">
                <a href="javascript: void(0);" class="image-popup">
                    <div class="image-wrapper">
                        <?= Html::img(Yii::getAlias('@web') .'/img/' . $item['img']) ?>
                    </div>
                </a>
                <header><h4><?= $item['title'] ?></h4></header>
                <div class="description">
                    <?= $item['description'] ?>
                </div><!-- for gluing together -->
            </div><!-- for gluing together -->
        </div><!-- for gluing together -->
    </div><!-- for gluing together -->
<?php endforeach; ?>
</div><!-- for gluing together -->

views/site/sections/sale.php
<?php
/**
 * Created: 28.05.18
 */
?>

<section id="sale" class="block">
    <div class="container">
        <header><h3>Праздничная акция</h3></header>
        <?= $this->render('sale/items') ?>
    </div><!-- for gluing together -->
</section><!-- for gluing together -->

views/site/sections/sale/items.php
<?php
/**
 * Created: 20.05.18
 */

use yii\helpers\Html;

$production = [
    [
        'img' => 'sale_07_01_25_t1.jpeg',
        'title' => 'Вертикальные жалюзи',
        'description' => '<dl>
                            <dt>Ткань "Франсе"</dt>
                            <dd><s>1850</s> 1400 руб / м<sup>2</sup></dd>
                            <dt>Ткань "Сорренто"</dt>
                            <dd><s>1850</s> 1400 руб / м<sup>2</sup></dd>
                            <dt>Ткань "Махаон"</dt>
                            <dd><s>1850</s> 1400 руб / м<sup>2</sup></dd>
                            <dt>Ткань "Амелия"</dt>
                            <dd><s>1850</s> 1400 руб / м<sup>2</sup></dd>
                        </dl>',
    ],
    [
        'img' => 'sale_07_01_25_bambuk_panda_t1.jpeg',
        'title' => 'Бамбуковые жалюзи',
        'description' => '<dl>
                            <dt>Панда</dt>
                            <dd><s>2850</s> 2200 руб / м<sup>2</sup></dd>
                            <dt style="visibility: hidden"> - </dt>
                            <dd style="visibility: hidden"> - </dd>
                            <dt style="visibility: hidden"> - </dt>
                            <dd style="visibility: hidden"> - </dd>
                            <dt style="visibility: hidden"> - </dt>
                            <dd style="visibility: hidden"> - </dd>
                        </dl>',
    ],
];

?>

<div class="row">
<?php foreach ($production as $item): ?>
    <div class="col-md-5 col-sm-6">
        <div class="property-wrapper">
            <div class="property">
                <a href="javascript: void(0);" class="image-popup">
                    <div class="image-wrapper sale-image-wrapper">
                        <?= Html::img(Yii::getAlias('@web') .'/img/' . $item['img']) ?>
                    </div>
                </a>
                <header><h4><?= $item['title'] ?></h4></header>
                <div class="description">
                    <?= $item['description'] ?>
                </div><!-- for gluing together -->
            </div><!-- for gluing together -->
        </div><!-- for gluing together -->
    </div><!-- for gluing together -->
<?php endforeach; ?>
</div><!-- for gluing together -->

views/site/sections/why_we.php
<?php
/** @var $this \yii\web\View*/

use yii\helpers\Html;

?>

<section id="features" class="block">
    <div class="container">
        <header><h3>Почему мы?</h3></header>
        <div class="row">
            <div class="col-md-4 col-sm-4">
                <ul class="features-list">
                    <li>1. Доступные цены</li>
                    <li>2. Высокое качество</li>
                    <li>3. Квалифицированные специалисты</li>
                    <li>4. Огромный выбор</li>
                    <li>5. Безупречная репутация компании</li>
                </ul><!-- for gluing together -->
            </div><!-- for gluing together -->
            <div class="col-md-8 col-sm-8">
                <div class="image-carousel">
                    <div class="image-carousel-slide">
                        <div class="row">
                            <div class="col-md-5 col-sm-5">
                                <?= Html::img(Yii::getAlias('@web') .'/img/gramota.jpeg', ['style' => 'display: none;']) ?>
                            </div>
                            <div class="col-md-7 col-sm-7">
                                <h4>Отзывы</h4>
                                <p><b>Виктор:</b>
                                    <?= $this->render('why_we/starts', ['count' => 5]) ?>
                                    <br>
                                    Индивидуальный подход, цена ниже, чем у других
                                </p>
                                <p><b>Инна:</b>
                                    <?= $this->render('why_we/starts', ['count' => 5]) ?>
                                    <br>
                                    Настоящие профессионалы, качественная установка
                                </p>
                                <p><b>Андрей:</b>
                                    <?= $this->render('why_we/starts', ['count' => 5]) ?>
                                    <br>
                                    Мы обратились в "ООО" Дом-сервис по рекомендации нашего знакомого, наш заказ был
                                    непростой, мало кто готов был браться, но ребята справились! Большое спасибо за профессионализм!
                                </p>
                                <iframe src="https://www.yandex.ru/sprav/widget/rating-badge/1095464614?type=rating&theme=dark" width="150" height="50" frameborder="0"></iframe>
                            </div>
                        </div><!-- for gluing together -->
                    </div><!-- for gluing together -->
                </div><!-- for gluing together -->
            </div><!-- for gluing together -->
        </div><!-- for gluing together -->
    </div><!-- for gluing together -->
</section><!-- for gluing together -->